import './app.js';
import mongoose from 'mongoose';
import { server, io } from './lib/socket.js';
import { validateConfig } from './lib/config.js';
validateConfig();
await mongoose.connect(process.env.MONGODB_URI, { serverSelectionTimeoutMS: 10000 });
server.listen(process.env.PORT || 5006, '0.0.0.0', () => console.log('Relay chat is ready'));
const stop = () => { io.close(); server.close(async () => { await mongoose.disconnect(); process.exit(0); }); setTimeout(() => process.exit(1), 10000).unref(); };
process.on('SIGTERM', stop);
process.on('SIGINT', stop);
